// Test the footer fix with more content to create multiple pages
const pdfGenerator = require('./pdfGenerator');

const testSong = {
    title: "Multi-Page Test Song",
    artist: "Footer Test Artist",
    lyrics: [
        "Verse 1:",
        "G    C    Am   F",
        "This is a very long test song",
        "G    C    Am   F", 
        "With many many verses",
        "G    C    Am   F",
        "To create multiple pages",
        "G    C    Am   F",
        "And test footer display",
        "",
        "Chorus:",
        "D    G    C    Am",
        "Test footer on each page",
        "D    G    C    Am",
        "Page numbers should show",
        "D    G    C    Am",
        "Generated by Discord bot",
        "D    G    C    Am",
        "September eleven today",
        "",
        "Verse 2:",
        "G    C    Am   F",
        "This verse continues testing",
        "G    C    Am   F",
        "Footer placement and spacing",
        "G    C    Am   F", 
        "Bottom margin should work",
        "G    C    Am   F",
        "Content should not overlap",
        "G    C    Am   F",
        "With the footer text below",
        "G    C    Am   F",
        "Testing line after line",
        "",
        "Bridge:",
        "Em   Am   D    G",
        "More content for page two",
        "Em   Am   D    G",
        "Testing page numbering",
        "Em   Am   D    G",
        "Should show 1/3, 2/3, 3/3",
        "Em   Am   D    G",
        "If we have three pages",
        "",
        "Verse 3:",
        "G    C    Am   F",
        "Adding even more content",
        "G    C    Am   F",
        "To ensure we get page three",
        "G    C    Am   F", 
        "Footer should appear there",
        "G    C    Am   F",
        "With proper page numbers",
        "G    C    Am   F",
        "Testing absolute positioning",
        "G    C    Am   F",
        "Of footer at page bottom",
        "",
        "Final Chorus:",
        "D    G    C    Am",
        "Footer fix is working",
        "D    G    C    Am",
        "On every single page",
        "D    G    C    Am",
        "With proper numbering format",
        "D    G    C    Am",
        "And no content overlap",
        "",
        "Outro:",
        "F    C    G    Am",
        "This should create enough",
        "F    C    G    Am",
        "Content for multiple pages",
        "F    C    G    Am",
        "To properly test footers",
        "F    C    G    Am",
        "And page number display",
        "F    C    G    Am",
        "The end of our test song",
        "F    C    G    Am",
        "Footer test complete!"
    ]
};

async function testMultiPageFooter() {
    try {
        console.log('🧪 Testing multi-page footer fix...');
        const pdfPath = await pdfGenerator.generatePDF(testSong);
        console.log(`✅ Multi-page PDF generated with footers: ${pdfPath}`);
    } catch (error) {
        console.error('❌ Test failed:', error);
    }
}

testMultiPageFooter();
