// Test the footer fix
const pdfGenerator = require('./pdfGenerator');

const testSong = {
    title: "Test Song",
    artist: "Test Artist",
    lyrics: [
        "Verse 1:",
        "G    C    Am   F",
        "This is a test song",
        "G    C    Am   F", 
        "With multiple verses",
        "",
        "Chorus:",
        "D    G    C    Am",
        "Test footer display",
        "D    G    C    Am",
        "On every page shown",
        "",
        "Verse 2:",
        "G    C    Am   F",
        "This verse is long enough",
        "G    C    Am   F",
        "To create multiple pages",
        "G    C    Am   F", 
        "And test the footer",
        "G    C    Am   F",
        "On each page properly",
        "",
        "Bridge:",
        "Em   Am   D    G",
        "Testing page numbers",
        "Em   Am   D    G",
        "Like 1/3, 2/3, 3/3",
        "",
        "Final Chorus:",
        "D    G    C    Am",
        "Footer should appear",
        "D    G    C    Am",
        "On every single page",
        "D    G    C    Am",
        "With proper numbering",
        "D    G    C    Am",
        "Generated by bot today"
    ]
};

async function testFooter() {
    try {
        console.log('🧪 Testing footer fix...');
        const pdfPath = await pdfGenerator.generatePDF(testSong);
        console.log(`✅ PDF generated with footers: ${pdfPath}`);
    } catch (error) {
        console.error('❌ Test failed:', error);
    }
}

testFooter();
